#ifndef HPP_HELP
#define HPP_HELP

#include <string>

const std::string g_strHelp = R"(
usage: ./profanity2 [OPTIONS]

  Quick start (auto key generation):
    -p, --prefix <hex>      Find address starting with given hex prefix.
    -x, --suffix <hex>      Find address ending with given hex suffix.

  Manual key mode:
    -z <128-hex-pubkey>     Provide seed public key (original profanity2 flow).

  Basic modes:
    --benchmark             Run without any scoring, a benchmark.
    --zeros                 Score on zeros anywhere in hash.
    --letters               Score on letters anywhere in hash.
    --numbers               Score on numbers anywhere in hash.
    --mirror                Score on mirroring from center.
    --leading-doubles       Score on hashes leading with hexadecimal pairs.
    -b, --zero-bytes        Score on hashes containing the most zero bytes.

  Modes with arguments:
    --leading <single hex>  Score on hashes leading with given hex character.
    --matching <hex string> Score on hashes matching given hex string.

  Advanced modes:
    --contract              Instead of account address, score the contract
                            address created by the account's zeroth transaction.
    --leading-range         Scores on hashes leading with characters within
                            given range.
    --range                 Scores on hashes having characters within given
                            range anywhere.

  Range:
    -m, --min <0-15>        Set range minimum (inclusive), 0 is '0' 15 is 'f'.
    -M, --max <0-15>        Set range maximum (inclusive), 0 is '0' 15 is 'f'.

  Device control:
    -s, --skip <index>      Skip device given by index.
    -n, --no-cache          Don't load cached pre-compiled version of kernel.

  Tweaking:
    -w, --work <size>       Set OpenCL local work size. [default = 64]
    -W, --work-max <size>   Set OpenCL maximum work size. [default = -i * -I]
    -i, --inverse-size      Set size of modular inverses to calculate in one
                            work item. [default = 255]
    -I, --inverse-multiple  Set how many above work items will run in
                            parallell. [default = 16384]

  Examples:
    ./profanity2 --prefix dead
    ./profanity2 --prefix dead --suffix beef
    ./profanity2 --prefix dead --contract
    ./profanity2 --benchmark
    ./profanity2 --matching badXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXbad -z <pubkey>

  About:
    profanity2 is a GPU-accelerated vanity address generator for Ethereum
    using OpenCL. Single binary, zero external dependencies.

  Credits:
    Original "profanity" by Johan Gustafsson <profanity@johgu.se>
    "profanity2" security fix by 1inch Network <info@1inch.io>
    Built-in key generation and --prefix/--suffix by mawom

  Disclaimer:
    Always verify that a private key generated by this program corresponds to
    the public key printed by importing it to a wallet of your choice. This
    program like any software might contain bugs and it does by design cut
    corners to improve overall performance.)";

#endif /* HPP_HELP */
